version: "3"
services:
  openspoolman:
    build: .
    env_file: "config.env"
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/home/app/logs
      - ./data:/home/app/data
      - ./prints:/home/app/static/prints